# Generated by Django 5.1.5 on 2025-01-30 18:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('api_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
